spring:
  application:
    name: blogr

  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql

springdoc:
  packages-to-scan: com.example.demo.controllers
  paths-to-exclude: /graphql









